baseurl = "https://blog.fmpwizard.com/"
languageCode = "en-us"
title = "FMPWizard's blog"

googleAnalytics = "UA-368436-11"
disqusShortname = "fmpwizard"

[permalinks]
    post = "/:year/:month/:day/:title/"
    page = "/:title/"

[[menu.main]]
    name = "About"
    url = "/about/"
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/fmpwizard"
[[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/fmpwizard"

[params]
    description = "Thoughts on Go, Golang, Lift, Scala and other technologies"

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
